import React, {useState} from 'react'

export default function Chatbot({selectedPlatforms, onToggle, onGenerate}){
  const [prompt, setPrompt] = useState('')
  const [loading, setLoading] = useState(false)
  const [togglingPlatforms, setTogglingPlatforms] = useState([])

  function makeDummyPost(platform, promptText){
    if(!promptText) return `Write a short update for ${platform}.`
    const base = promptText.trim()
    switch(platform){
      case 'twitter':
        return base.length>260 ? base.slice(0,257) + '...' : base + ' #Tweet'
      case 'facebook':
        return base + '\n\nShared on Facebook.'
      case 'linkedin':
        return base + '\n\nProfessional update for LinkedIn.'
      case 'reddit':
        return base + '\n\nPosted to Reddit (subreddit placeholder).'
      case 'discord':
        return base + ' (shared in server)'
      case 'telegram':
        return base + ' (shared on channel)'
      default:
        return base
    }
  }

  async function handleGenerate(){
    setLoading(true)
    await new Promise(r => setTimeout(r, 600))
    const posts = {}
    for(const p of togglingPlatforms){
      posts[p] = makeDummyPost(p, prompt || `Hello ${p} audience! This is an autogenerated post.`)
    }
    setLoading(false)
    onGenerate(posts)
  }

  function togglePlatform(key){
    setTogglingPlatforms(prev => prev.includes(key) ? prev.filter(p=>p!==key) : [...prev, key])
  }

  return (
    <div style={{border:'1px solid #333', padding:16, borderRadius:8, background:'#1a1a1a'}}>
      <h3 style={{marginTop:0, marginBottom:4, color:'#fff'}}>Post Generator</h3>
      <p style={{marginTop:0, marginBottom:12, color:'#999', fontSize:13}}>Write a prompt, select platforms, and generate platform-specific posts.</p>
      
      <textarea 
        value={prompt} 
        onChange={e=>setPrompt(e.target.value)} 
        placeholder="Enter your message here..." 
        style={{
          width:'100%',
          height:80,
          padding:10,
          borderRadius:6,
          border:'1px solid #333',
          background:'#111',
          color:'#e0e0e0',
          fontFamily:'inherit',
          fontSize:13,
          resize:'vertical'
        }} 
      />
      
      <div style={{marginTop:12, marginBottom:12}}>
        <div style={{color:'#999', fontSize:12, marginBottom:6}}>Select platforms to post to:</div>
        <div style={{display:'flex', flexWrap:'wrap', gap:8}}>
          {selectedPlatforms.map(p => (
            <button
              key={p}
              onClick={() => togglePlatform(p)}
              style={{
                padding:'6px 12px',
                borderRadius:6,
                background: togglingPlatforms.includes(p) ? '#4ade80' : '#333',
                color: togglingPlatforms.includes(p) ? '#111' : '#aaa',
                border:'1px solid ' + (togglingPlatforms.includes(p) ? '#4ade80' : '#444'),
                cursor:'pointer',
                fontSize:12,
                fontWeight:600,
                transition:'all 0.2s'
              }}
            >
              {togglingPlatforms.includes(p) ? '✓' : '◯'} {p}
            </button>
          ))}
        </div>
      </div>

      <div style={{display:'flex',gap:8,marginTop:12}}>
        <button 
          onClick={handleGenerate} 
          disabled={loading || togglingPlatforms.length===0} 
          style={{
            padding:'10px 16px',
            cursor:'pointer',
            background:'#4ade80',
            color:'#111',
            border:'none',
            borderRadius:6,
            fontWeight:600,
            transition:'all 0.2s'
          }}
        >
          {loading? 'Generating...' : 'Generate Posts'}
        </button>
        <div style={{alignSelf:'center', color:'#999', fontSize:13}}>
          {togglingPlatforms.length===0 ? 'Select platforms above' : `${togglingPlatforms.length} platform(s) selected`}
        </div>
      </div>
    </div>
  )
}
