import React, {useState} from 'react'

export default function Chatbot({selectedPlatforms, onToggle, onGenerate}){
  const [prompt, setPrompt] = useState('')
  const [loading, setLoading] = useState(false)
  const [togglingPlatforms, setTogglingPlatforms] = useState([])

  function makeDummyPost(platform, promptText){
    if(!promptText) return `Write a short update for ${platform}.`
    const base = promptText.trim()
    switch(platform){
      case 'twitter':
        return base.length>260 ? base.slice(0,257) + '...' : base + ' #Tweet'
      case 'facebook':
        return base + '\n\nShared on Facebook.'
      case 'linkedin':
        return base + '\n\nProfessional update for LinkedIn.'
      case 'reddit':
        return base + '\n\nPosted to Reddit (subreddit placeholder).'
      case 'discord':
        return base + ' (shared in server)'
      case 'telegram':
        return base + ' (shared on channel)'
      default:
        return base
    }
  }

  async function handleGenerate(){
    setLoading(true)
    await new Promise(r => setTimeout(r, 600))
    const posts = {}
    for(const p of togglingPlatforms){
      posts[p] = makeDummyPost(p, prompt || `Hello ${p} audience! This is an autogenerated post.`)
    }
    setLoading(false)
    onGenerate(posts)
  }

  function togglePlatform(key){
    setTogglingPlatforms(prev => prev.includes(key) ? prev.filter(p=>p!==key) : [...prev, key])
  }

  return (
    <div className="surface-card chatbot-panel">
      <div className="chatbot-header">
        <div className="section-label">Composer</div>
        <h3>Post Generator</h3>
      </div>
      <p className="chatbot-copy">Write a prompt, select platforms, and generate platform-specific posts.</p>
      
      <textarea 
        value={prompt} 
        onChange={e=>setPrompt(e.target.value)} 
        placeholder="Enter your message here..." 
        className="chatbot-textarea"
      />
      
      <div className="chatbot-platforms">
        <div className="chatbot-subtitle">Select platforms to post to:</div>
        <div className="chatbot-chip-row">
          {selectedPlatforms.map(p => (
            <button
              key={p}
              onClick={() => togglePlatform(p)}
              className={togglingPlatforms.includes(p) ? 'chip-button active' : 'chip-button'}
            >
              {togglingPlatforms.includes(p) ? '✓' : '◯'} {p}
            </button>
          ))}
        </div>
      </div>

      <div className="chatbot-footer">
        <button 
          onClick={handleGenerate} 
          disabled={loading || togglingPlatforms.length===0} 
          className="generate-button"
        >
          {loading? 'Generating...' : 'Generate Posts'}
        </button>
        <div className="chatbot-status">
          {togglingPlatforms.length===0 ? 'Select platforms above' : `${togglingPlatforms.length} platform(s) selected`}
        </div>
      </div>
    </div>
  )
}
